# Generated by Django 5.2.10 on 2026-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(blank=True, help_text='Login/apelido do operador', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_password_setup',
            field=models.BooleanField(default=False, help_text='True se operador precisa definir senha no primeiro login'),
        ),
    ]
