# Generated by Django 5.2.10 on 2026-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.TextField(blank=True, help_text='Token JWT da sessão atual', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
