# Generated by Django 6.0.2 on 2026-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('BALCAO', 'Balcão'), ('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada')], default='BALCAO', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pix_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
