# Generated by Django 6.0.2 on 2026-02-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_change_amount_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
