# Generated by Django 5.2.10 on 2026-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_address_order_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REALIZADO', 'Realizado'), ('PREPARANDO', 'Preparando'), ('ENVIADO', 'Enviado'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='REALIZADO', max_length=20),
        ),
    ]
