# Generated by Django 5.2.10 on 2026-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='operators_limit',
            field=models.IntegerField(default=1, help_text='Número máximo de operadores permitidos nesta chave'),
        ),
    ]
