# Generated by Django 5.2.10 on 2026-02-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_licensekey_operators_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='managers_limit',
            field=models.IntegerField(default=1, help_text='Número máximo de gerentes permitidos nesta chave'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(choices=[('basico', 'Básico'), ('pro', 'Pro'), ('enterprise', 'Enterprise'), ('free', 'Free')], unique=True),
        ),
    ]
