# Generated by Django 6.0.2 on 2026-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
