# Generated by Django 5.2.10 on 2026-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_agent_active_customer_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_segment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
