# Generated by Django 5.2.10 on 2026-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_business_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_retention_notified',
            field=models.BooleanField(default=False, help_text='Notificado sobre retenção/exclusão'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Consente receber marketing via WhatsApp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy_accepted',
            field=models.BooleanField(default=False, help_text='Aceite da Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy_version',
            field=models.CharField(default='1.0', help_text='Versão da política aceita', max_length=20),
        ),
    ]
