# Generated by Django 5.2.10 on 2026-02-28 13:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_data_retention_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf_cnpj',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
