# Generated by Django 6.0.2 on 2026-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('whatsapp', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('out_of_hours_message', models.TextField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bot_active', models.BooleanField(default=True)),
            ],
        ),
    ]
