# Generated by Django 5.2.10 on 2026-02-28 13:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_cashier_report_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
