# Generated by Django 5.2.10 on 2026-02-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Visualizou'), ('LIST', 'Listou'), ('EXPORT', 'Exportou'), ('EDIT', 'Editou'), ('DELETE', 'Excluiu'), ('SEARCH', 'Buscou'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('resource_type', models.CharField(help_text='Ex: customer, order, user', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso a Dados',
                'verbose_name_plural': 'Logs de Acesso a Dados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_dataac_user_id_c6ea17_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_dataac_resourc_864cdb_idx'), models.Index(fields=['action', 'created_at'], name='core_dataac_action_800401_idx')],
            },
        ),
    ]
